Repository LeonardoTPereira/Overlord-Project, pull requests merged in 2022-05, with the labels that each got.

#129 Creates SO to save rooms and an example fo room generation using said SO
  Assets/Scripts/Game/LevelManager/DungeonLoader/RoomData.cs
  Assets/Scripts/Game/LevelManager/DungeonLoader/RoomData.cs.meta
  Assets/Scripts/Game/LevelManager/DungeonLoader/RoomGeneratorInput.cs
  Assets/Scripts/Game/LevelManager/DungeonLoader/RoomGeneratorInput.cs.meta
  Assets/Scripts/Game/LevelManager/DungeonLoader/SaveRoomExample.cs
  Assets/Scripts/Game/LevelManager/DungeonLoader/SaveRoomExample.cs.meta
Labels: enhancement

#130 Populate questlines
  Assets/Resources/PlayerQuestionModels.meta
  Assets/Resources/ScriptableObjectsData/NpcSOs/NarrativeTests.meta
  Assets/Resources/ScriptableObjectsData/NpcSOs/NarrativeTests/Narrative_ (Game.NarrativeGenerator.Quests.GetQuestSO).asset
  Assets/Resources/ScriptableObjectsData/NpcSOs/NarrativeTests/Narrative_ (Game.NarrativeGenerator.Quests.GetQuestSO).asset.meta
  Assets/Scenes/NarrativeGenerator/NarrativeUITests.unity
  Assets/Scripts/Game/NarrativeGenerator/QuestGeneratorManager.cs
  Assets/Scripts/Game/NarrativeGenerator/QuestUI.cs
  Assets/Scripts/Game/NarrativeGenerator/QuestWeightsManager.cs
  Assets/Scripts/Game/NarrativeGenerator/QuestWeightsManager.cs.meta
  Assets/Scripts/Game/NarrativeGenerator/Quests/MarkovChains/MakovChain.cs
  Assets/Scripts/Game/NarrativeGenerator/Quests/QuestGrammarNonterminals/Explore.cs
  Assets/Scripts/Game/NarrativeGenerator/Quests/QuestGrammarNonterminals/Get.cs
  Assets/Scripts/Game/NarrativeGenerator/Quests/QuestGrammarNonterminals/Kill.cs
  Assets/Scripts/Game/NarrativeGenerator/Quests/QuestGrammarNonterminals/NonTerminalQuest.cs
  Assets/Scripts/Game/NarrativeGenerator/Quests/QuestGrammarNonterminals/Start.cs
  Assets/Scripts/Game/NarrativeGenerator/Quests/QuestGrammarNonterminals/Start.cs.meta
  Assets/Scripts/Game/NarrativeGenerator/Quests/QuestGrammarNonterminals/Symbol.cs
  Assets/Scripts/Game/NarrativeGenerator/Quests/QuestGrammarNonterminals/Talk.cs
  Assets/Scripts/Game/NarrativeGenerator/Quests/QuestGrammarTerminals/DropQuestSo.cs
  Assets/Scripts/Game/NarrativeGenerator/Quests/QuestGrammarTerminals/EmptyQuestSO.cs
  Assets/Scripts/Game/NarrativeGenerator/Quests/QuestGrammarTerminals/GetQuestSo.cs
  Assets/Scripts/Game/NarrativeGenerator/Quests/QuestGrammarTerminals/ItemQuestSo.cs
  Assets/Scripts/Game/NarrativeGenerator/Quests/QuestGrammarTerminals/KillQuestSO.cs
  Assets/Scripts/Game/NarrativeGenerator/Quests/QuestGrammarTerminals/SecretRoomQuestSO.cs
  Assets/Scripts/Game/NarrativeGenerator/Quests/QuestGrammarTerminals/TalkQuestSO.cs
  Assets/Scripts/Game/NarrativeGenerator/Quests/QuestLine.cs
  Assets/Scripts/Game/NarrativeGenerator/Quests/QuestSO.cs
  Assets/Scripts/Game/NarrativeGenerator/Quests/QuestTerminals.meta
  Assets/Scripts/Game/NarrativeGenerator/Quests/Symbol.cs
  Assets/Scripts/Game/NarrativeGenerator/Quests/Symbol.cs.meta
  Assets/Scripts/Game/NarrativeGenerator/Quests/nao_terminais.meta
  Assets/Scripts/Game/NarrativeGenerator/Selector.cs
  Assets/Scripts/Util/Constants.cs
  pyModel
Labels: enhancement

#131 Fixes merge from new Quest Generator and Real Time Generator
  Assets/Inputs/PlayerInputAction.cs
  Assets/Inputs/PlayerInputAction.cs.meta
  Assets/Scripts/Game/GameManager/GameManagerSingleton.cs
  Assets/Scripts/Game/GameManager/LevelLoaderBHV.cs
  Assets/Scripts/Game/LevelManager/DungeonLoader/DungeonSceneLoader.cs
  Assets/Scripts/Game/LevelManager/DungeonLoader/DungeonSceneManager.cs
  Assets/Scripts/Game/NarrativeGenerator/ProfileCalculator.cs
  Assets/Scripts/Game/NarrativeGenerator/ProfileCalculator.cs.meta
  Assets/Scripts/Game/NarrativeGenerator/ProfileWeightCalculator.cs
  Assets/Scripts/Game/NarrativeGenerator/QuestGeneratorManager.cs
  Assets/Scripts/Game/NarrativeGenerator/QuestWeightsCalculator.cs
  Assets/Scripts/Game/NarrativeGenerator/QuestWeightsCalculator.cs.meta
  Assets/Scripts/Game/NarrativeGenerator/QuestWeightsManager.cs
  Assets/Scripts/Game/NarrativeGenerator/Quests/QuestGrammarNonterminals/Get.cs
  Assets/Scripts/Game/NarrativeGenerator/Quests/QuestGrammarNonterminals/Talk.cs
  Assets/Scripts/Game/NarrativeGenerator/Quests/QuestGrammarTerminals/EmptyQuestSO.cs
  Assets/Scripts/Game/NarrativeGenerator/Quests/QuestLine.cs
  Assets/Scripts/Game/NarrativeGenerator/Quests/QuestSO.cs
  Assets/Scripts/Game/NarrativeGenerator/Selector.cs
  Assets/Scripts/Game/Quests/IQuestElement.cs
  Assets/Scripts/Game/Quests/IQuestElement.cs.meta
  Assets/Scripts/Game/Quests/PlaceholderCollectableQuestElement.cs
  Assets/Scripts/Game/Quests/PlaceholderCollectableQuestElement.cs.meta
  Assets/Scripts/Game/Quests/PlaceholderCountableQuestElement.cs
  Assets/Scripts/Game/Quests/PlaceholderCountableQuestElement.cs.meta
  Assets/Scripts/Game/Quests/PlaceholderQuestController.cs
  Assets/Scripts/Game/Quests/QuestController.cs
  Assets/Scripts/Game/Quests/QuestController.cs.meta
  Assets/Scripts/Game/Quests/QuestCountableElementEvent.cs
  Assets/Scripts/Game/Quests/QuestElementEvent.cs
  Assets/Scripts/Game/Quests/QuestElementEventArgs.cs
  Assets/Scripts/Game/Quests/QuestElementEventArgs.cs.meta
  Assets/Scripts/Game/Quests/QuestGetItemEventArgs.cs
  Assets/Scripts/Game/Quests/QuestGetItemEventArgs.cs.meta
  Assets/Scripts/Game/Quests/QuestKillEnemyEventArgs.cs
  Assets/Scripts/Game/Quests/QuestKillEnemyEventArgs.cs.meta
  Assets/Scripts/Util/Enums.cs
  ProjectSettings/BurstAotSettings_StandaloneWindows.json
Labels: bug

#132 Narative generator/balancing
  Assets/Scripts/Game/NarrativeGenerator/Quests/QuestGrammarTerminals/DropQuestSo.cs
  Assets/Scripts/Game/NarrativeGenerator/Selector.cs
  Assets/Scripts/Util/Constants.cs
Labels: bug, enhancement
